const headphones = [
  {
    id: 1,
    name: "P47 Bluetooth Headphone Black",
    name2:"P47BluetoothHeadphoneBlack",
    images: [
      require("../assets/images/a1.png"),
      require("../assets/images/a2.png"),
      require("../assets/images/a3.png"),
      require("../assets/images/a4.png"),
    ],
    image: require("../assets/images/a1.png"),
    des: "",
    price: 9,
  },
  {
    id: 2,
    name: "P47 Bluetooth Headphone Music Headset.Black",
    name2:"P47BluetoothHeadphoneMusicHeadset.Black",
    images: [
      require("../assets/images/b1.png"),
      require("../assets/images/b2.png"),
      require("../assets/images/b3.png"),
      require("../assets/images/b4.png"),
    ],
    image: require("../assets/images/b1.png"),
    des: "",
    price: 10,
  },
  {
    id: 3,
    name: "Beexcellent GM-1 Gaming Headset PS4 Video",
    name2:"BeexcellentGM-1GamingHeadsetPS4Video",
    images: [
      require("../assets/images/c1.png"),
      require("../assets/images/c2.png"),
      require("../assets/images/c3.png"),
      require("../assets/images/c4.png"),
    ],
    image: require("../assets/images/c1.png"),
    des: "",
    price: 8,
  },
  {
    id: 4,
    name: "P47 Bluetooth 5.0Wireless Mic Support TFCard FM",
    name2:"P47Bluetooth5.0WirelessMicSupportTFCardFM",
    images: [
      require("../assets/images/d1.png"),
      require("../assets/images/d2.png"),
      require("../assets/images/d3.png"),
      require("../assets/images/d4.png"),
    ],
    image: require("../assets/images/d1.png"),
    des: "",
    price: 10,
  },
  {
    id: 5,
    name: "P47 Bluetooth 6.0Wireless TF Card FM Radio White",
    name2:"P47Bluetooth6.0WirelessTFCardFMRadioWhite",
    images: [
      require("../assets/images/e1.png"),
      require("../assets/images/e2.png"),
      require("../assets/images/e3.png"),
      require("../assets/images/e4.png"),
    ],
    image: require("../assets/images/e1.png"),
    des: "",
    price: 10,
  },
  {
    id: 6,
    name: "P47 Bluetooth 5.0Wireless TF Card FM Radio White",
    name2:"P47Bluetooth5.0WirelessTFCardFMRadioWhite",
    images: [
      require("../assets/images/f1.png"),
      require("../assets/images/f2.png"),
      require("../assets/images/f3.png"),
      require("../assets/images/f4.png"),
    ],
    image: require("../assets/images/f1.png"),
    des: "",
    price: 9,
  },
  {
    id: 7,
    name: "Zealot B20 Headphone Wireless Stereo Earphone",
    name2:"ZealotB20HeadphoneWirelessStereoEarphone",
    images: [
      require("../assets/images/g1.png"),
      require("../assets/images/g2.png"),
      require("../assets/images/g3.png"),
      require("../assets/images/g4.png"),
    ],
    image: require("../assets/images/g1.png"),
    des: "",
    price: 6,
  },
  {
    id: 8,
    name: "Borofone Wireless Headphones With Inbuilt",
    name2:"BorofoneWirelessHeadphonesWithInbuilt",
    images: [
      require("../assets/images/h1.png"),
      require("../assets/images/h2.png"),
      require("../assets/images/h3.png"),
      require("../assets/images/h4.png"),
    ],
    image: require("../assets/images/h1.png"),
    des: "",
    price: 9,
  },
];
export default headphones
